version: "3.8"

services:
  encryption_service:
    build:
      context: ./services/encryption
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - kms_service

  kms_service:
    build:
      context: ./services/kms
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge